### ISSUE TITLE
Can you also support ipq807x?

### ISSUE THREAD

**Issue by huangya90** [Hanszhang2023/Qsdk_build_image#1]
Hi,

Thanks for your sharing. Would you also add support for ipq807x?

**Comment by Hanszhang2023** [comment]
Thank you for your reply.I Will update it.


Best regards

quanhai zhang

---- Replied Message ----
| From | ***@***.***> |
| Date | 05/17/2024 14:15 |
| To | Hanszhang2023/Qsdk_build_image ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [Hanszhang2023/Qsdk_build_image] Can you also support ipq807x? (Issue #1) |

Hi,

Thanks for your sharing. Would you also add support for ipq807x?

**Comment by huangya90** [comment]
I have seen them. However, would you also upload 64bit versions? It's a waste for those modes with much memory if 64bit version is not used. Thanks.

**Comment by Hanszhang2023** [comment]
I usually update 32bit image.


Best regards

quanhai zhang

---- Replied Message ----
| From | ***@***.***> |
| Date | 05/20/2024 14:56 |
| To | Hanszhang2023/Qsdk_build_image ***@***.***> |
| Cc | Hans ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [Hanszhang2023/Qsdk_build_image] Can you also support ipq807x? (Issue #1) |

I have seen them. However, would you also upload 64bit versions? It's a waste for those modes with much memory if 64bit version is not used. Thanks.

**Comment by huangya90** [comment]
> I usually update 32bit image. Best regards quanhai zhang
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 05/20/2024 14:56 | | To | Hanszhang2023/Qsdk_build_image ***@***.***> | | Cc | Hans ***@***.***>, Comment ***@***.***> | | Subject | Re: [Hanszhang2023/Qsdk_build_image] Can you also support ipq807x? (Issue #1) | I have seen them. However, would you also upload 64bit versions? It's a waste for those modes with much memory if 64bit version is not used. Thanks. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Because IPQ807x is armv8 , only 64bit version can unleash its full power like armv8 Crypto Extensions, which accelerates crypto operations.

**Comment by Hanszhang2023** [comment]
qca-networking-2022-spf-12-2/IPQ807x/csu3/premium_64bit  updated.

**Comment by huangya90** [comment]
> qca-networking-2022-spf-12-2/IPQ807x/csu3/premium_64bit updated.

Thanks a lot
