### ISSUE TITLE
ipq5018的设备可以直接替换你的这个固件吗？

### ISSUE THREAD

**Issue by wzzhanghong** [Hanszhang2023/Qsdk_build_image#2]
ipq5018的设备可以直接替换你的这个固件吗？

**Comment by Hanszhang2023** [comment]
具体要看 你的硬件设计和原厂的硬件设计区别大不大


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月28日 00:54 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

ipq5018的设备可以直接替换你的这个固件吗？

**Comment by wzzhanghong** [comment]
ipq5018为什么只有32bit？
single和app分别代表什么意思？一个是系统，一个是uboot？
高通的uboot阉割很多命令，比如nand dump等，是否可以补全？
另外如果我要在qwrt上安装openwrt的其他插件，一定要重新编译吗？

**Comment by Hanszhang2023** [comment]
32bit 对于熟悉环境就够用了，uboot本身也是32bit，kernel 可以是64bit。
app image 在线升级的时候只包括kernel 和rootfs，不包括boot相关的。
nand dump 这些命令是有的，只是看不到help 信息


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月16日 00:28 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

ipq5018为什么只有32bit？
single和app分别代表什么意思？一个是系统，一个是uboot？
高通的uboot阉割很多命令，比如nand dump等，是否可以补全？

**Comment by wzzhanghong** [comment]
﻿﻿﻿﻿谢谢你的回复！那是否qsdk编译的openwrt都可以用你的app img来更新吗？我在我的这个设备的uboot上执行nand dump没有任何反应，不知道是怎么回事。我找到的qsdk 从来没编译成功过，是下载的包有问题吗？如果要安装openwrt 的插件，是否一定要重新编译才可以？在 2024年6月16日，14:15，Hans ***@***.***> 写道：﻿
32bit 对于熟悉环境就够用了，uboot本身也是32bit，kernel 可以是64bit。
app image 在线升级的时候只包括kernel 和rootfs，不包括boot相关的。
nand dump 这些命令是有的，只是看不到help 信息


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月16日 00:28 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

ipq5018为什么只有32bit？
single和app分别代表什么意思？一个是系统，一个是uboot？
高通的uboot阉割很多命令，比如nand dump等，是否可以补全？

**Comment by Hanszhang2023** [comment]
我觉得是可以的


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月16日 23:53 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

﻿﻿﻿﻿谢谢你的回复！那是否qsdk编译的openwrt都可以用你的app img来更新吗？我在我的这个设备的uboot上执行nand dump没有任何反应，不知道是怎么回事。我找到的qsdk 从来没编译成功过，是下载的包有问题吗？如果要安装openwrt 的插件，是否一定要重新编译才可以？在 2024年6月16日，14:15，Hans ***@***.***> 写道：﻿
32bit 对于熟悉环境就够用了，uboot本身也是32bit，kernel 可以是64bit。
app image 在线升级的时候只包括kernel 和rootfs，不包括boot相关的。
nand dump 这些命令是有的，只是看不到help 信息


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月16日 00:28 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

ipq5018为什么只有32bit？
single和app分别代表什么意思？一个是系统，一个是uboot？
高通的uboot阉割很多命令，比如nand dump等，是否可以补全？

**Comment by Hanszhang2023** [comment]
有ipk 是可以安装的
不过，我都是下载ipk源码包，整合到sdk里。
你可以尝试一下。












--

Best regards

quanhai zhang




在 2024-06-16 22:53:32，"wzzhanghong" ***@***.***> 写道：

﻿﻿﻿﻿谢谢你的回复！那是否qsdk编译的openwrt都可以用你的app img来更新吗？我在我的这个设备的uboot上执行nand dump没有任何反应，不知道是怎么回事。我找到的qsdk 从来没编译成功过，是下载的包有问题吗？如果要安装openwrt 的插件，是否一定要重新编译才可以？在 2024年6月16日，14:15，Hans ***@***.***> 写道：﻿
32bit 对于熟悉环境就够用了，uboot本身也是32bit，kernel 可以是64bit。
app image 在线升级的时候只包括kernel 和rootfs，不包括boot相关的。
nand dump 这些命令是有的，只是看不到help 信息


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月16日 00:28 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

ipq5018为什么只有32bit？
single和app分别代表什么意思？一个是系统，一个是uboot？
高通的uboot阉割很多命令，比如nand dump等，是否可以补全？

**Comment by wzzhanghong** [comment]
好的，谢谢你的建议，我去尝试一下。冒昧问一下，可否分享一下你的qsdk 包？在 2024年6月18日，14:42，Hans ***@***.***> 写道：﻿
有ipk 是可以安装的
不过，我都是下载ipk源码包，整合到sdk里。
你可以尝试一下。












--

Best regards

quanhai zhang




在 2024-06-16 22:53:32，"wzzhanghong" ***@***.***> 写道：

﻿﻿﻿﻿谢谢你的回复！那是否qsdk编译的openwrt都可以用你的app img来更新吗？我在我的这个设备的uboot上执行nand dump没有任何反应，不知道是怎么回事。我找到的qsdk 从来没编译成功过，是下载的包有问题吗？如果要安装openwrt 的插件，是否一定要重新编译才可以？在 2024年6月16日，14:15，Hans ***@***.***> 写道：﻿
32bit 对于熟悉环境就够用了，uboot本身也是32bit，kernel 可以是64bit。
app image 在线升级的时候只包括kernel 和rootfs，不包括boot相关的。
nand dump 这些命令是有的，只是看不到help 信息


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月16日 00:28 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

ipq5018为什么只有32bit？
single和app分别代表什么意思？一个是系统，一个是uboot？
高通的uboot阉割很多命令，比如nand dump等，是否可以补全？

**Comment by Hanszhang2023** [comment]
这个资源需要付费


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月18日 21:56 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

好的，谢谢你的建议，我去尝试一下。冒昧问一下，可否分享一下你的qsdk 包？在 2024年6月18日，14:42，Hans ***@***.***> 写道：﻿
有ipk 是可以安装的
不过，我都是下载ipk源码包，整合到sdk里。
你可以尝试一下。












--

Best regards

quanhai zhang




在 2024-06-16 22:53:32，"wzzhanghong" ***@***.***> 写道：

﻿﻿﻿﻿谢谢你的回复！那是否qsdk编译的openwrt都可以用你的app img来更新吗？我在我的这个设备的uboot上执行nand dump没有任何反应，不知道是怎么回事。我找到的qsdk 从来没编译成功过，是下载的包有问题吗？如果要安装openwrt 的插件，是否一定要重新编译才可以？在 2024年6月16日，14:15，Hans ***@***.***> 写道：﻿
32bit 对于熟悉环境就够用了，uboot本身也是32bit，kernel 可以是64bit。
app image 在线升级的时候只包括kernel 和rootfs，不包括boot相关的。
nand dump 这些命令是有的，只是看不到help 信息


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月16日 00:28 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

ipq5018为什么只有32bit？
single和app分别代表什么意思？一个是系统，一个是uboot？
高通的uboot阉割很多命令，比如nand dump等，是否可以补全？

**Comment by wzzhanghong** [comment]
什么价格？在 2024年6月19日，09:46，Hans ***@***.***> 写道：﻿
这个资源需要付费


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月18日 21:56 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

好的，谢谢你的建议，我去尝试一下。冒昧问一下，可否分享一下你的qsdk 包？在 2024年6月18日，14:42，Hans ***@***.***> 写道：﻿
有ipk 是可以安装的
不过，我都是下载ipk源码包，整合到sdk里。
你可以尝试一下。












--

Best regards

quanhai zhang




在 2024-06-16 22:53:32，"wzzhanghong" ***@***.***> 写道：

﻿﻿﻿﻿谢谢你的回复！那是否qsdk编译的openwrt都可以用你的app img来更新吗？我在我的这个设备的uboot上执行nand dump没有任何反应，不知道是怎么回事。我找到的qsdk 从来没编译成功过，是下载的包有问题吗？如果要安装openwrt 的插件，是否一定要重新编译才可以？在 2024年6月16日，14:15，Hans ***@***.***> 写道：﻿
32bit 对于熟悉环境就够用了，uboot本身也是32bit，kernel 可以是64bit。
app image 在线升级的时候只包括kernel 和rootfs，不包括boot相关的。
nand dump 这些命令是有的，只是看不到help 信息


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月16日 00:28 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

ipq5018为什么只有32bit？
single和app分别代表什么意思？一个是系统，一个是uboot？
高通的uboot阉割很多命令，比如nand dump等，是否可以补全？

**Comment by Hanszhang2023** [comment]
加我qq吧86174397


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月19日 12:56 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

什么价格？在 2024年6月19日，09:46，Hans ***@***.***> 写道：﻿
这个资源需要付费


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月18日 21:56 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

好的，谢谢你的建议，我去尝试一下。冒昧问一下，可否分享一下你的qsdk 包？在 2024年6月18日，14:42，Hans ***@***.***> 写道：﻿
有ipk 是可以安装的
不过，我都是下载ipk源码包，整合到sdk里。
你可以尝试一下。












--

Best regards

quanhai zhang




在 2024-06-16 22:53:32，"wzzhanghong" ***@***.***> 写道：

﻿﻿﻿﻿谢谢你的回复！那是否qsdk编译的openwrt都可以用你的app img来更新吗？我在我的这个设备的uboot上执行nand dump没有任何反应，不知道是怎么回事。我找到的qsdk 从来没编译成功过，是下载的包有问题吗？如果要安装openwrt 的插件，是否一定要重新编译才可以？在 2024年6月16日，14:15，Hans ***@***.***> 写道：﻿
32bit 对于熟悉环境就够用了，uboot本身也是32bit，kernel 可以是64bit。
app image 在线升级的时候只包括kernel 和rootfs，不包括boot相关的。
nand dump 这些命令是有的，只是看不到help 信息


Best regards

quanhai zhang

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月16日 00:28 |
| 收件人 | Hanszhang2023/Qsdk_build_image ***@***.***> |
| 抄送人 | Hans ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [Hanszhang2023/Qsdk_build_image] ipq5018的设备可以直接替换你的这个固件吗？ (Issue #2) |

ipq5018为什么只有32bit？
single和app分别代表什么意思？一个是系统，一个是uboot？
高通的uboot阉割很多命令，比如nand dump等，是否可以补全？
